version: "3.8"

services:
    app:
        image: aditnugroho/laravel-api:latest
        container_name: laravel-api
        restart: unless-stopped
        tty: true
        working_dir: /var/www/laravel-api
        volumes:
            - ./:/var/www/laravel-api
        networks:
            - laravel
        environment:
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=laravel_api
            - DB_USERNAME=root
            - DB_PASSWORD=200405

    nginx:
        image: nginx:alpine
        container_name: nginx
        restart: unless-stopped
        ports:
            - "8080:80"
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./:/var/www/laravel-api
        networks:
            - laravel

    db:
        image: mysql:latest
        container_name: mysql
        restart: unless-stopped
        ports:
            - "3307:3306"
        environment:
            MYSQL_ROOT_PASSWORD: 200405
            MYSQL_DATABASE: laravel_api
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - laravel

volumes:
    db_data:

networks:
    laravel:
        driver: bridge
